name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime Coding Stats
    runs-on: ubuntu-latest

    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE: True
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_COMMIT: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LOC_CHART: False
          LOCALE: en
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}